[tool.poetry]
name = "odyssey"
version = "0.6"
description = "Calcula la ruta mas optima para el repostaje de gasolina en un viaje"
authors = ["jose <josevilchez4@correo.ugr.es>"]

[tool.poetry.dependencies]
pylint = "^2.11.1"

[tool.poetry.dev-dependencies]
python = "^3.8"
invoke = "^1.6.0"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
