[tool.poetry]
name = "odyssey"
version = "0.7"
description = "Calcula la ruta más óptima para el repostaje de gasolina en un viaje"
authors = ["jose <josevilchez4@correo.ugr.es>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
invoke = "^1.6.0"
pylint = "^2.11.1"
pytest = "^6.2.5"
assertpy = "^1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
