[tool.poetry]
name = "odyssey"
version = "0.7"
description = "Calcula la ruta mas optima para el repostaje de gasolina en un viaje"
authors = ["jose <josevilchez4@correo.ugr.es>"]

[tool.poetry.dependencies]
python = ">=3.7"

[tool.poetry.dev-dependencies]
poethepoet = "^0.11.0"
virtualenv = "^20.14.1"

[tool.poetry.plugins."poetry.application.plugin"]
poethepoet = "poethepoet.plugin:PoetryPlugin"

[tool.poe.tasks]

   [tool.poe.tasks.test]
   help = "Run unit and feature tests"
   cmd  = "pytest --cov=poethepoet"

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
