name: Publish Docker image
on:
  push:
    paths:
      - poetry.lock
      - pyproject.toml
      - Dockerfile
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  build-and-push-images:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Build and push Docker Image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/odyssey
          tags: latest
